version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  aws-cli: circleci/aws-cli@4.0.0

jobs:
  login-to-aws:
    docker: &docker_image
      - image: 'cimg/ruby:3.1.3-node'
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: $ECR_ROLE_TO_ASSUME # this will use the env var
          region: $ECR_REGION # this will use the env var
      - run: &ecr_login
          name: Login to ecr
          command: |
            aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com
            aws configure export-credentials --format env
      - run: |
          cp $BASH_ENV bash.env
      - persist_to_workspace:
          root: .
          paths:
            - bash.env
  test:
    working_directory: ~/circle
    docker:
      - image: docker.io/ministryofjustice/fb-builder:latest
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
          DATABASE_URL: postgresql://root@localhost/fb-publisher_test
      - image: cimg/postgres:10.19
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test
    steps:
      - checkout
      - setup_remote_docker: &remote_docker
          docker_layer_caching: true
      - run:
          name: test
          command: 'make spec'
      - slack/status: &slack_status
          fail_only: true
          only_for_branches: master
          failure_message: ":facepalm:  Failed job $CIRCLE_JOB  :homer-disappear:"
          include_job_number_field: false
  build_and_push_web_image:
    working_directory: ~/circle/git/fb-publisher
    docker: &ecr_base_image
      - image: docker.io/ministryofjustice/fb-builder:latest
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker: *remote_docker
      - attach_workspace:
          at: .
      - run: &workspace_envs
          command: |
            cat bash.env >> $BASH_ENV
      - run: &base_environment_variables
          name: Setup base environment variable
          command: |
            echo "export BUILD_SHA=$CIRCLE_SHA1" >> $BASH_ENV
            echo "export SSH_FILE_FOR_SECRETS=~/.ssh/id_rsa_65357fbcc65a92dfff23ac166c2e76de" >> $BASH_ENV
      - run: &deploy_scripts
          name: cloning deploy scripts
          command: 'git clone --branch temporary-ecr-creds git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: test
            BUILD_WORKER: false
          command: './deploy-scripts/bin/build'
      - slack/status: *slack_status
  build_and_push_worker_image:
    working_directory: ~/circle/git/fb-publisher
    docker: *ecr_base_image
    steps:
      - checkout
      - setup_remote_docker: *remote_docker
      - attach_workspace:
          at: .
      - run: *workspace_envs
      - run: *base_environment_variables
      - aws-cli/setup:
          role_arn: $WORKERS_ECR_ROLE_TO_ASSUME # this will use the env var
          region: $ECR_REGION # this will use the env var
      - run: *deploy_scripts
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: test
            BUILD_WORKER: 'true'
          command: './deploy-scripts/bin/build'
      - slack/status: *slack_status
  deploy_to_test:
    working_directory: ~/circle/git/fb-publisher
    docker: *ecr_base_image
    steps:
      - checkout
      - setup_remote_docker: *remote_docker
      - add_ssh_keys: &ssh_keys
          fingerprints:
            - 65:35:7f:bc:c6:5a:92:df:ff:23:ac:16:6c:2e:76:de
      - run: *base_environment_variables
      - run: *deploy_scripts
      - run:
          name: deploy to test environment in EKS
          environment:
            APPLICATION_NAME: fb-publisher
            PLATFORM_ENV: test
            K8S_NAMESPACE: formbuilder-publisher-test
          command: './deploy-scripts/bin/deploy-eks'
      - slack/status: *slack_status
  deploy_to_live:
    working_directory: ~/circle/git/fb-publisher
    docker: *ecr_base_image
    steps:
      - checkout
      - setup_remote_docker: *remote_docker
      - add_ssh_keys: *ssh_keys
      - run: *base_environment_variables
      - run: *deploy_scripts
      - run:
          name: deploy to live (eks)
          environment:
            APPLICATION_NAME: fb-publisher
            PLATFORM_ENV: live
            K8S_NAMESPACE: formbuilder-publisher-live
          command: './deploy-scripts/bin/deploy-eks'
      - slack/status:
          only_for_branches: master
          success_message: ":rocket:  Successfully deployed to Live  :guitar:"
          failure_message: ":alert:  Failed to deploy to Live  :try_not_to_cry:"
          include_job_number_field: false

workflows:
  version: 2
  test_and_build:
    jobs:
      - login-to-aws:
          context: &context
            - moj-forms
      - test:
          context: *context
          requires:
            - login-to-aws
      - build_and_push_web_image:
          context: *context
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - build_and_push_worker_image:
          context: *context
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy_to_test:
          context: *context
          requires:
            - build_and_push_web_image
            - build_and_push_worker_image
      - slack/approval-notification:
          message: ":portalorangeparrot:  Deployment to Live pending approval  :portalblueparrot:"
          include_job_number_field: false
          requires:
            - deploy_to_test
      - confirm_live_deploy:
          type: approval
          requires:
            - deploy_to_test
      - deploy_to_live:
          context: *context
          requires:
            - confirm_live_deploy
